from packages.core.process_ir.extractor import extract
from packages.core.process_ir.similarity import (
    AliasGroup,
    DimensionScore,
    ProcessCluster,
    ProcessFingerprint,
    SimilarityScore,
    cluster_processes,
    detect_aliases,
    make_fingerprint,
    score_similarity,
)
from packages.core.process_ir.types import (
    ActionClass,
    ActionClassification,
    ControlType,
    EntityType,
    ExtractionMethod,
    ExtractionResult,
    ExtractedEntity,
    ExtractedRelation,
    RelationType,
    TemporalCue,
)
from packages.core.schemas.process_ir import (
    ChangeEvent,
    Control,
    DecisionPoint,
    EvidenceRef,
    ProcessException,
    ProcessIR,
    Role,
    SystemTouchpoint,
    WorkflowStep,
)

__all__ = [
    # ProcessIR schema types
    "ProcessIR",
    "WorkflowStep",
    "DecisionPoint",
    "SystemTouchpoint",
    "Role",
    "Control",
    "ProcessException",
    "ChangeEvent",
    "EvidenceRef",
    # Extraction types
    "extract",
    "ExtractionResult",
    "ExtractedEntity",
    "ExtractedRelation",
    "ActionClassification",
    "TemporalCue",
    "EntityType",
    "RelationType",
    "ActionClass",
    "ControlType",
    "ExtractionMethod",
    # Similarity types
    "ProcessFingerprint",
    "SimilarityScore",
    "DimensionScore",
    "AliasGroup",
    "ProcessCluster",
    "make_fingerprint",
    "score_similarity",
    "detect_aliases",
    "cluster_processes",
]
