from packages.core.process_ir.extractor import extract
from packages.core.process_ir.graph import (
    GraphEdge,
    GraphNode,
    WorkflowGraph,
    project_graph,
)
from packages.core.process_ir.lineage import (
    ChangeCategory,
    LineageChain,
    ProcessVersion,
    TimelineEvent,
    aggregate_changes,
    build_lineage_chain,
    build_timeline,
    build_timeline_summary,
    detect_superseded,
)
from packages.core.process_ir.similarity import (
    AliasGroup,
    DimensionScore,
    ProcessCluster,
    ProcessFingerprint,
    SimilarityScore,
    cluster_processes,
    detect_aliases,
    make_fingerprint,
    score_similarity,
)
from packages.core.process_ir.types import (
    ActionClass,
    ActionClassification,
    ControlType,
    EntityType,
    ExtractionMethod,
    ExtractionResult,
    ExtractedEntity,
    ExtractedRelation,
    RelationType,
    TemporalCue,
)
from packages.core.schemas.process_ir import (
    ChangeEvent,
    Control,
    DecisionPoint,
    EvidenceRef,
    ProcessException,
    ProcessIR,
    Role,
    SystemTouchpoint,
    WorkflowStep,
)

__all__ = [
    # ProcessIR schema types
    "ProcessIR",
    "WorkflowStep",
    "DecisionPoint",
    "SystemTouchpoint",
    "Role",
    "Control",
    "ProcessException",
    "ChangeEvent",
    "EvidenceRef",
    # Extraction types
    "extract",
    "ExtractionResult",
    "ExtractedEntity",
    "ExtractedRelation",
    "ActionClassification",
    "TemporalCue",
    "EntityType",
    "RelationType",
    "ActionClass",
    "ControlType",
    "ExtractionMethod",
    # Graph projection types
    "GraphNode",
    "GraphEdge",
    "WorkflowGraph",
    "project_graph",
    # Lineage types
    "ChangeCategory",
    "TimelineEvent",
    "ProcessVersion",
    "LineageChain",
    "build_timeline",
    "build_lineage_chain",
    "aggregate_changes",
    "detect_superseded",
    "build_timeline_summary",
    # Similarity types
    "ProcessFingerprint",
    "SimilarityScore",
    "DimensionScore",
    "AliasGroup",
    "ProcessCluster",
    "make_fingerprint",
    "score_similarity",
    "detect_aliases",
    "cluster_processes",
]
